credentials:
  usernames:
    admin:
      email: st124956@ait.asia
      name: Lu Kyaw
      password: "$2b$12$g8QmBpbGStaZ7RkSanwHMu0oN9pijDOAIIUkmUyLZFlkg7JKx92Ke" # password admin123
cookie:
  expiry_days: 30
  key: olist_ecommerce_2025_key
  name: olist_app_cookie
preauthorized:
  emails: []